### ISSUE TITLE
Slurm manager timeout error 

### ISSUE THREAD

**Issue by fnthibaud** [doyle-lab-ucla/auto-qchem#1]
When running the code of the Tutorial_creating_descriptor_sets.ipynb notebook in jupyter-notebooks, the "ServerSelectionTimeoutError" is raised.

I apologize in advance, I am a chemist with little programming experience, so if more detail is needed, please let me know.

**Comment by zuranski** [comment]
Hello,

It is a timeout for connection to the descriptor database. As of now the code connects to a local database to which we cannot grant access. One could use the code and omit all the DB parts, and submission of calculations to the computing cluster, and use it more manually, however a bit of programming experience would be required. If there is something specific you'd like to do, maybe I could help.

Best,
Andrzej

**Comment by fnthibaud** [comment]
Hello Andrzej,

Thanks for the kind reply. My intention was to create DFT descriptors for a small set of chemicals for subsequent use in EDBO (express). I've attached a .xlsx file with the corresponding smile strings. If you happen to have time to run these in your program, I'd be very grateful. 

Best, 
Fabien



[smiles_strings.xlsx](https://github.com/PrincetonUniversity/auto-qchem/files/6554158/smiles_strings.xlsx)

**Comment by beef-broccoli** [comment]
close this for now
