### ISSUE TITLE
500 Internal Server Error on Database Website

### ISSUE THREAD

**Issue by Sn1perMcMarc** [doyle-lab-ucla/auto-qchem#28]
When visiting https://autoqchem.org/ the navbar is displayed but no content on the site appears.

Checking the console log shows this:

>500 Internal Server ErrorInternal Server Error<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>message: "Callback error updating page-content.children"

**Comment by beef-broccoli** [comment]
fixed
