### ISSUE TITLE
How to do quantum computation when there are 3 or more non-bonded fragments?

### ISSUE THREAD

**Issue by stephenokj78** [doyle-lab-ucla/auto-qchem#4]
Through molecule.py, it is possible to count up to 2 or less non-bonded fragments.

For molecules with 3 or more non-bonded fragments, such as K2CO3, how can we do quantum calculations?

**Comment by beef-broccoli** [comment]
it really depends on what calculation you want to do. It doesn't really make sense to calculate it as a "molecule"
