### ISSUE TITLE
Consider adding a description to the repo and some tags

### ISSUE THREAD

**Issue by sgbaird** [doyle-lab-ucla/auto-qchem#9]
![image](https://user-images.githubusercontent.com/45469701/164947687-a338b9c3-f754-4ab3-9ab5-851dc9779d4f.png)

Not something I can add as a PR, but e.g. "Machine learning tools for the automated computation of chemical, thermochemical, and steric features of molecules" (adapted the snippet from https://github.com/b-shields/auto-QChem)

For tags, maybe add:
- https://github.com/topics/cheminformatics

Random, for extra visibility you could also submit a PR to https://github.com/hsiaoyi0504/awesome-cheminformatics

**Comment by zuranski** [comment]
Thanks for the suggestions, I updated the metadata!
